### ISSUE TITLE
Frontend to-do-list

### ISSUE THREAD

**Issue by xlepotato** [xlepotato/CloudComputingTrainingSystem#3]
# **NOTE:** Better if all the fields name or words can be written in Chinese. You can write in English first and change later after my backend integration if it is faster for you to come out with frontend pages. Also, if there are pages that I did not mention here, just add it below. Thanks 💯 😄  ### If anything unsure, can always ask me.

If see the ⭐️ , it means important & try to do that first 

- [x] ⭐️ ⭐️  Register page fields :  (remember to give the correct input type ( for example password textfield input type should be password instead of text & etc)
- 用户名： 
- 密码：
- 重复密码：
- 姓名：
- 电子邮件:
- 验证码:

- [x] ⭐️ ⭐️ Update Particular page:   ( have another button in this page to link to the change password page)
- Username
- name
- email

- [x] Change password page:
- previous password
- new password
- confirm new password

- [x] Homepage after logging in ( student & teacher)

=ADMIN LOGIN FUNCTIONS=
2 navigation tab here:
- [x] ⭐️  Student (consist of a button at the top right above the table for Adding new student account, another button beside add new student button for saving data into excel spreadsheet, view all student page, data displayed in table with 2 button in each cell ( update / remove)
- [x] ⭐️ Teacher  ( consist of a button at the top right above the table for Adding new teacher account,another button beside add new teacher button for saving data into excel spreadsheet, view all teachers page, data displayed in table with 2 button in each cell( update / remove)

- [x] Add student / teacher account page: Must have the same fields as register page except that it does not have the email textfield & the captcha field.

- [x] ⭐️ ⭐️ ⭐️  Quiz question display page ( Just give me the new blank template, i write my backend codes to display the radio button & checkboxes first, then afterwards u do the styling on those radiobutton/checkboxes/alignment & etc )

- [x] ⭐️ ⭐️ ⭐️  Score display page ( Just give me the new blank template, i write my backend codes to display the radio button & checkboxes first, then afterwards u do the styling on those radiobutton/checkboxes/alignment & etc )

- [x] Grading page :
- Show all the exercise quiz name in a List view kind of look( for example now there is only 2 ) and have a link/button <Click to see result> to link to the score page.
- Somewhere at the top, display the total grade / score the user has gotten. The score , and the grade ( A / B+ / B / C+ & etc) Just write it like static score/grade first, so I know that the space is for displaying score / grade)

- [x] Check for all html pages title and ensure that it is correctly named / not blank

- [x] Create a Logo

- [x] Teachers upload assignment page

- [x] Teacher view and download all student submitted assignment page

- [x] Student submit assignment page

- [x] Student view all assignment page

- [x] Styling of relevant pages

- [x] Front-end validation for login, registration, change the password and update particulars form.

- [x] Solve missing grades and score (front-end) of the quiz review and quiz results page

- [x] Creating of Adding student and teacher users for admin

- [x] Linking all relevant pages for admin

- [x] Change user password for admin

- [x] Update user information

- [x] Update teacher information for admin

- [x] Change password for teacher in admin page
